import math
import os
import struct
import zstd

from os import path
from PIL import Image, ImageFile
from sys import argv, stderr


def main():
    if len(argv) < 2:
        print("usage: packfiles.py <directory> [-raw]")
        return

    dir = argv[1]
    if not path.exists(dir):
        print(f"{dir} doesn't exist")
        return

    raw = False
    if len(argv) > 2 and argv[2] == "-raw":
        raw = True

    # walk and scan all the files to add
    entries = []
    data = bytearray()
    for root, dirs, files in os.walk(dir, topdown=False):
        for file in files:
            file_data = bytes()
            name = file
            ext_split = path.splitext(file)
            # process images
            if len(ext_split) > 1 and ext_split[1] in [".png"]:
                print(f"// converting image {file}")
                name = f"{ext_split[0]}.img"
                img = Image.open(path.join(root, file))
                pixels = img.get_flattened_data()
                file_data = bytearray()
                for pixel in pixels:
                    full = list(pixel) + [0xFF] * (4 - len(pixel))
                    #full.reverse()
                    #print(full)
                    for byte in full:
                        file_data.append(byte)
            else:
                with open(path.join(root, file), "rb") as f:
                    file_data = f.read()

            entries.append({"name": name, "size": len(file_data)})
            print(f"// adding {file} as {entries[-1]}")
            data.extend(file_data)

    print(f"// compressing {len(data)} byte(s) from {len(entries)} entries")
    compressed = zstd.compress(bytes(data), 9)

    data = bytearray(
        struct.pack("<III", len(data), len(compressed), len(entries))
    )  # totalSize and entryCount
    for entry in entries:
        data.extend(
            struct.pack("<16sI", bytes(entry["name"], encoding="utf-8"), entry["size"])
        )
    print(f"// header is {len(data)} bytes")
    print(
        f"// compressed data is {len(compressed)} bytes ({compressed[:5]}...{compressed[-4:]})"
    )

    data.extend(compressed)
    print(f"// total is {len(data)}")
    if raw:
        with open("demo.pak", "wb") as f:
            f.write(data)
    else:
        code = f'// autogenerated demo pack\nextern "C" unsigned char g_fileTable[{len(data)}] = {{\n\t'
        n = 4
        for byte in data:
            code += f"0x{byte:02x},"
            n += 6
            if n >= 80:
                n = 4
                code += "\n\t"
            else:
                code += " "
        code += "\n};"
        print(code)


if __name__ == "__main__":
    main()
