import lzma
import os
import struct

from os import path
from sys import argv, stderr


def main():
    if len(argv) < 2:
        print("usage: packfiles.py <directory> [-raw]")
        return
    
    dir = argv[1]
    if not path.exists(dir):
        print(f"{dir} doesn't exist")
        return
    
    raw = False
    if len(argv) > 2 and argv[2] == "-raw":
        raw = True

    # walk and scan all the files to add
    entries = []
    data = bytearray()
    for root, dirs, files in os.walk(dir, topdown=False):
        for file in files:
            file_data = bytes()
            with open(path.join(root, file), "rb") as f:
                file_data = f.read()
            entries.append({ 'name': file, 'size': len(file_data) })
            print(f"// adding {entries[-1]}")
            data.extend(file_data)

    print(f"// compressing {len(data)} byte(s) from {len(entries)} entries")
    compressed = lzma.compress(data, lzma.FORMAT_XZ)

    data = bytearray(struct.pack("<III", len(data), len(compressed), len(entries))) # totalSize and entryCount
    for entry in entries:
        data.extend(struct.pack("<16sI", bytes(entry["name"], encoding="utf-8"), entry["size"]))
    print(f"// header is {len(data)} bytes")
    print(f"// compressed data is {len(compressed)} bytes ({compressed[:5]}...{compressed[-4:]})")
    
    data.extend(compressed)
    print(f"// total is {len(data)}")
    if raw:
        with open("demo.pak", "wb") as f:
            f.write(data)
    else:
        code = f"// autogenerated demo pack\nextern \"C\" unsigned char g_fileTable[{len(data)}] = {{\n\t"
        n = 4
        for byte in data:
            code += f"0x{byte:02x},"
            n += 6
            if n >= 80:
                n = 4
                code += "\n\t"
            else:
                code += " "
        code += "\n};"
        print(code)
    

if __name__ == "__main__":
    main()
